"""add admin pin to announcements

Revision ID: 1b159c348e7e
Revises: fd79dfed99db
Create Date: 2026-07-28 03:33:30.943303

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b159c348e7e"
down_revision: str | Sequence[str] | None = "fd79dfed99db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements", sa.Column("admin_pin", sa.String(length=4), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "admin_pin")
    # ### end Alembic commands ###
